### ISSUE TITLE
如何手动触发下载toml？

### ISSUE THREAD

**Issue by SMAXLYB** [twiceyuan/remote-version-catalog#2]
除了定时更新下载toml，如何手动触发下载

**Comment by twiceyuan** [comment]
配置插件后项目级别 Tasks 下会有个 `remote-version-catalog` 的 group，下面会有一个 `downloadRemoteVersionCatalog` 的任务是手动触发下载。回头我更新下 README，谢谢关注

**Comment by twiceyuan** [comment]
已在 2989c3f1468b9879bbbca9cf9fd7f525e7adbd25 补充说明
